version: '3'
services:
  main:
    build: .
    restart: always
    environment:
      PROFILE:
      DB_PASSWORD:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
